server:
  port: 8080
camel:
  springboot:
    name: ServicesRest
management:
  port: 8081
edpoints:
  enabled: true
  health:
    enabled: true
quickstart:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
simplecloud:
  api:
    path: '/camel'